from __future__ import annotations

DEFAULT_APP_NAME = "sentinel-agent"
DEFAULT_DB_FILENAME = "sentinel.db"
DEFAULT_LOG_FILENAME = "app.log"
DEFAULT_AUDIT_FILENAME = "audit.log"
DEFAULT_VECTOR_DIRNAME = "vector"
DEFAULT_CACHE_DIRNAME = "cache"
DEFAULT_RUNTIME_DIRNAME = "runtime"
DEFAULT_LOG_DIRNAME = "logs"
DEFAULT_AUDIT_DIRNAME = "audit"

DEFAULT_MAX_STEPS_PER_TURN = 6
DEFAULT_MAX_TOOL_CALLS_PER_TURN = 4
DEFAULT_WALL_CLOCK_SECONDS = 60
DEFAULT_MEMORY_TOP_K = 8
DEFAULT_TOOL_OUTPUT_CHARS = 12_000
DEFAULT_MEMORY_SNIPPET_CHARS = 1_500
DEFAULT_APPROVAL_TTL_SECONDS = 900
DEFAULT_EMBEDDING_DIM = 384

TRACE_EVENT_TURN_STARTED = "turn_started"
TRACE_EVENT_PLAN_CREATED = "plan_created"
TRACE_EVENT_POLICY_DECISION = "policy_decision"
TRACE_EVENT_TOOL_STARTED = "tool_started"
TRACE_EVENT_TOOL_FINISHED = "tool_finished"
TRACE_EVENT_RESPONSE_READY = "response_ready"
TRACE_EVENT_TURN_FINISHED = "turn_finished"

SENSITIVE_ENV_KEYS = {
    "SENTINEL_GROQ_API_KEY",
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "AWS_SECRET_ACCESS_KEY",
}
