from __future__ import annotations

from typing import Protocol, Sequence

from sentinel.domain.common.ids import MemoryId
from sentinel.domain.memory.entities import MemoryEntry, MemorySnapshot, RetrievalBundle


class MemoryRepositoryPort(Protocol):
    def save(self, memory: MemoryEntry) -> None: ...
    def get(self, memory_id: MemoryId) -> MemoryEntry | None: ...
    def search_lexical(self, query: str, limit: int) -> list[MemoryEntry]: ...
    def list_recent(self, limit: int) -> list[MemoryEntry]: ...
    def delete(self, memory_id: MemoryId) -> None: ...


class EmbeddingPort(Protocol):
    def embed(self, text: str) -> list[float]: ...


class RetrieverPort(Protocol):
    def retrieve(self, query: str, limit: int) -> RetrievalBundle: ...


class SummarizerPort(Protocol):
    async def summarize(self, text: str) -> str: ...
    async def summarize_many(self, items: Sequence[str]) -> MemorySnapshot: ...
