from __future__ import annotations

from typing import Protocol


class PackageManagerAdapter(Protocol):
    async def search(self, package: str) -> str: ...
    async def info(self, package: str) -> str: ...
    async def query_installed(self, package: str | None = None) -> str: ...
    async def preview(self, operation: str, packages: list[str]) -> str: ...
    async def apply(self, operation: str, packages: list[str]) -> str: ...
